### PR TITLE
Suuport cubic curves in TTGlyphPen

### PR DESCRIPTION
**Pull request by khaledhosny**
Using https://github.com/googlei18n/cu2qu to convert cubic to quadratic curves. This can be then used to convert CFF charstrings to glyf glyphs.

I kept the commits as this evolved with @anthrotype help, but I guess the commits should be squashed before merging.

### CODE REVIEW

**Comment by behdad** [comment]
Interesting.

I don't think it should be folded into TTGlyphPen().

Best would be to have a separate Cu2QuPen and use pen composition.

**Comment by anthrotype** [comment]
> Best would be to have a separate Cu2QuPen and use pen composition.

Yeah, that's what I did as well originally, but didn't find the time to clean it up and contribute it to the cu2u repository. I made a "filter" pen that takes another one (which can be either a "drawing" pen or another filter pen) in its constructor, applies its transformations before passing on the instructions downstream (e.g. see `fontTools.pens.transformPen`, or `robofab.pens.filterPen`).

Maybe it'd be better if such a general use Cu2QuPen (as well as a Cu2QuPointPen that follows the robofab pen protocol) should belong to the cu2qu package itself rather than fonttools.

**Comment by adrientetar** [comment]
> Maybe it'd be better if such a general use Cu2QuPen (as well as a Cu2QuPointPen that follows the robofab pen protocol) belong to the cu2qu package itself rather than fonttools.

My thoughts exactly, I had written something similar. Maybe it should be called in ufo2ft though.

**Comment by khaledhosny** [comment]
All this pen stuff is really allover my head, I just wanted a way to convert CFF to glyf using FontTools, and I’m happy with whatever direction you settle on.

**Comment by adrientetar** [comment]
Well I think so far we all agree that this should be in the cu2qu package, could you submit a PR there?

Thanks for this, by the way.

**Comment by anthrotype** [comment]
I'm on it, I should be done by today.

**Comment by twardoch** [comment]
The Pen protocol is a specific one in that various pens are often far more useful beyond the context they've been implemented in. Ultimately, I'd really like to try to "centralize" them a bit into a single repo, or at least location. This is the list of RoboFab-compatible pens that I was able to find on Github. Some of them are probably very specifically tied to a given library, but others are generally useful but almost impossible to discover. 
* [behdad/fonttools/tree/master/Lib/fontTools/pens](https://github.com/behdad/fonttools/tree/master/Lib/fontTools/pens) 
* [robofab-developers/robofab/tree/master/Lib/robofab/pens](https://github.com/robofab-developers/robofab/tree/master/Lib/robofab/pens) 
* [asaumierdemers/UFOarchive](https://github.com/asaumierdemers/UFOarchive) 
* [bluemoon/crayons/blob/master/pypaint/types/text.py](https://github.com/bluemoon/crayons/blob/master/pypaint/types/text.py) 
* [fontfont/RoboChrome/tree/master/RoboChrome.roboFontExt/lib/colorfont](https://github.com/fontfont/RoboChrome/tree/master/RoboChrome.roboFontExt/lib/colorfont) 
* [gferreira/hTools2/blob/master/Lib/hTools2/modules/pens.py](https://github.com/gferreira/hTools2/blob/master/Lib/hTools2/modules/pens.py) 
* [google/roboto/blob/master/scripts/lib/fontbuild/curveFitPen.py](https://github.com/google/roboto/blob/master/scripts/lib/fontbuild/curveFitPen.py) 
* [googlei18n/compreffor/blob/master/tools/subr_grapher.py](https://github.com/googlei18n/compreffor/blob/master/tools/subr_grapher.py) 
* [googlei18n/nototools/blob/master/nototools/glyph_area_pen.py](https://github.com/googlei18n/nototools/blob/master/nototools/glyph_area_pen.py) 
* [houseind/robothon/blob/master/GlyphProofer/Lib/glyphProoferLib/toPDF.py](https://github.com/houseind/robothon/blob/master/GlyphProofer/Lib/glyphProoferLib/toPDF.py) 
* [jenskutilek/RedArrow/blob/master/RedArrow.roboFontExt/lib/outlineTestPen.py](https://github.com/jenskutilek/RedArrow/blob/master/RedArrow.roboFontExt/lib/outlineTestPen.py) 
* [jenskutilek/RoboFont/blob/master/scripts-test/Audio/midiPen.py](https://github.com/jenskutilek/RoboFont/blob/master/scripts-test/Audio/midiPen.py) 
* [LettError/responsiveLettering/blob/master/ResponsiveLettering.roboFontExt/lib/mathShape/mathImageSVGPathPen.py](https://github.com/LettError/responsiveLettering/blob/master/ResponsiveLettering.roboFontExt/lib/mathShape/mathImageSVGPathPen.py) 
* [loicsander/MutatorScale/tree/master/lib/mutatorScale/pens](https://github.com/loicsander/MutatorScale/tree/master/lib/mutatorScale/pens) 
* [loicsander/RobofabPens](https://github.com/loicsander/RobofabPens) 
* [loicsander/Robofont-scripts/blob/master/CornerTools/CornerTools.roboFontExt/lib/glyphObjects.py](https://github.com/loicsander/Robofont-scripts/blob/master/CornerTools/CornerTools.roboFontExt/lib/glyphObjects.py) 
* [loicsander/Robofont-scripts/tree/master/PenBallWizard/PenBallWizard.roboFontExt/lib/penBallWizard/objects](https://github.com/loicsander/Robofont-scripts/tree/master/PenBallWizard/PenBallWizard.roboFontExt/lib/penBallWizard/objects) 
* [loicsander/Robofont-scripts/tree/master/ScaleFast/ScaleFast.roboFontExt/lib/mutatorScale/pens](https://github.com/loicsander/Robofont-scripts/tree/master/ScaleFast/ScaleFast.roboFontExt/lib/mutatorScale/pens) 
* [mcguffin/SplitBezier/blob/master/SplitBezier.py](https://github.com/mcguffin/SplitBezier/blob/master/SplitBezier.py) 
* [ninastoessinger/Touche/tree/master/Touche.roboFontExt/lib/touche](https://github.com/ninastoessinger/Touche/tree/master/Touche.roboFontExt/lib/touche) 
* [trufont/trufont/blob/master/Lib/defconQt/representationFactories/qPainterPathFactory.py](https://github.com/trufont/trufont/blob/master/Lib/defconQt/representationFactories/qPainterPathFactory.py) 
* [typemytype/drawBotRoboFontExtension/blob/master/DrawBot.roboFontExt/lib/drawBot/context/baseContext.py](https://github.com/typemytype/drawBotRoboFontExtension/blob/master/DrawBot.roboFontExt/lib/drawBot/context/baseContext.py) 
* [typemytype/RoboFontExamples/tree/master/pens](https://github.com/typemytype/RoboFontExamples/tree/master/pens) 
* [typesupply/aicbTools/blob/master/Lib/aicbTools.py](https://github.com/typesupply/aicbTools/blob/master/Lib/aicbTools.py) 
* [typesupply/defcon/blob/master/Lib/defcon/tools/booleanOperations/flatten.py](https://github.com/typesupply/defcon/blob/master/Lib/defcon/tools/booleanOperations/flatten.py) 
* [typesupply/defconAppKit/blob/master/Lib/defconAppKit/representationFactories/nsBezierPathFactory.py](https://github.com/typesupply/defconAppKit/blob/master/Lib/defconAppKit/representationFactories/nsBezierPathFactory.py) 
* [typesupply/glyph-nanny/blob/master/Glyph%20Nanny.roboFontExt/lib/glyphNanny.py](https://github.com/typesupply/glyph-nanny/blob/master/Glyph%20Nanny.roboFontExt/lib/glyphNanny.py) 
* [typesupply/ufo2fdk/tree/master/Lib/ufo2fdk/pens](https://github.com/typesupply/ufo2fdk/tree/master/Lib/ufo2fdk/pens) 
* [typesupply/ufo2svg/blob/master/Lib/ufo2svg/svgPathPen.py](https://github.com/typesupply/ufo2svg/blob/master/Lib/ufo2svg/svgPathPen.py) 
* [yanone/ynlib/blob/master/Lib/ynlib/pens.py](https://github.com/yanone/ynlib/blob/master/Lib/ynlib/pens.py)

**Comment by twardoch** [comment]
Ps. There was some talk a few months ago about starting a new package, independent of fontTools or RoboFab, which could be a "curated pen collection". It could be organized into subfolders by its main or "toughest" dependency. Its policy for accepting contributions could be a bit more relaxed than the rest, akin to the [RoboFab objects](https://github.com/robofab-developers/robofab/tree/master/Lib/robofab/objects) folder where there is objectsFF.py which is not necessarily superbly tested and has external depedencies on the `fontforge` Python package while the rest of the modules in RoboFab don't have it).

**Comment by LettError** [comment]
Two quick points:
1. objectsFF.py is very dead and should only serve as an example of "dead".

2. a couple of pens could probably be weaned from Robofab, but many of the pens on your list really belong with their packages. Moving them out would create an unwelcome mess of dependencies and practical problems. Just because the code follows certain a pattern does not make it useful to collect them all in one place. 

Erik

**Comment by adrientetar** [comment]
> Moving them out would create an unwelcome mess of dependencies and practical problems.

I tend to agree with this. What would be most useful is a directory of pens with a description for each of them so you can find quickly if there is one suitable for your needs.

**Comment by twardoch** [comment]
Erik, 

The list I posted is "unfiltered" i.e. I just searched Github for any code portions that inherit from the basic fontTools pens. Probably 75% of those aren't useful to be centralized, and they're pretty trivial. But there are some that would be. And the colleagues are now talking about having more pens implemented, including some that are definitely of general usefulness.

**Comment by graphicore** [comment]
As stated elsewhere, I'm doing a "just pens library" in JavaScript. I think it's a good idea to do this. It's a work in progress: [graphicore/Atem-Pen-Case](https://github.com/graphicore/Atem-Pen-Case).

To handle dependencies, I suggest to do dependency injection. Right now, I have a good and a bad example.

Good: [SVGPen](https://github.com/graphicore/Atem-Pen-Case/blob/master/lib/pens/SVGPen.js). That pen expects an instance of SVGPathElement (html5) in its constructor. The dependency is not tied to the library, but to the caller.

```js
    /*constructor*/
    function SVGPen(path, glyphSet) {
        Parent.call(this, glyphSet);
        this.path = path;
        this.segments = path.pathSegList;
    }
```

Bad: [OpenTypePen](https://github.com/graphicore/Atem-Pen-Case/blob/master/lib/pens/OpenTypePen.js). That pen uses the opentype.js `Path` constructor in its constructor and thus creates a dependency of the library itself to opentype.js. I just realized my mistake and I'll fix this later ;-)

```js
    /*constructor*/
    function OpenTypePen (glyphSet) {
        Parent.call(this, glyphSet);
        this.path = new OTPath();
    }
```

Dependency Injection could be all it needs to collect these pens in a central library. It surely would be nice to have a basic pen for some of the common UI toolkits, like a `QTPen`, `CairoPen`, `CocoaPen` and I'm sure they can all be implemented with dependency injection. Further, thanks to duck typing, it may be really easy to adopt existing pens to new environments.

**Comment by twardoch** [comment]
Please check https://github.com/robofab-developers/robofab/issues/52

**Comment by jackjennings** [comment]
Off-topic (sorry): I just posted a link to a list of pens in some core packages—including `fonttools`—on the issue that Adam linked to. If possible, it would be helpful to get some core `fonttools` developers to help figure out which of the pens in this package don't have additional dependencies and might be useful outside of the `fonttools` context.

**Comment by khaledhosny** [comment]
Closing this then.

**Pull request closed without merging**
