### PR TITLE
[OS/2] fix misspellings 'usMaxContext', 'usFirstCharIndex', 'usLastCh…

### PR DESCRIPTION
**Pull request by anthrotype**
Fixes https://github.com/behdad/fonttools/issues/74

### CODE REVIEW

**Comment by davelab6** [comment]
I think this came up before and there was a concern that fixing it would break legacy scripts, so perhaps you could add a 2nd commit that allows legacy scripts to continue to work?

**Comment by anthrotype** [comment]
You're right. What about this https://github.com/behdad/fonttools/commit/e63cbe8d3c16ef0460e52ad8880c2b9998a2e182?

**Comment by davelab6** [comment]
Looks perfect to me :)

**Comment by anthrotype** [comment]
I tried to fix misspellings with other misspellings! Thank you @djdm for spotting them.
I rebased and squashed the new commit into the previous one.

**Comment by behdad** [comment]
I'm also concerned about people who build tables in code.  Perhaps better way to fix this is to provide properties for the wrong values.  Or just ignore this problem and accept them as historical artifacts.

**Comment by anthrotype** [comment]
Thanks for the suggestion. Yes, it makes more sense to use properties.
I changed it accordingly and rebased. Please let me know if it's OK now.

**Pull request merged**
