### PR TITLE
[trak] add AAT 'trak' table support

### PR DESCRIPTION
**Pull request by anthrotype**
The internal structure of the new `table__t_r_a_k` looks like this: 

```python
table.__dict__ = {
		'version': 1.0,
		'format': 0,
		'horizData': TrackData({
			-1.0: TrackTableEntry(
				{9.0: -10, 10.0: -30, 19.0: -63, 12.0: -60, 18.0: -63}, nameIndex=275),
			 0.0: TrackTableEntry(
			 	{9.0: 15, 10.0: 0, 19.0: -25, 12.0: -5, 18.0: -25}, nameIndex=303),
			 1.0: TrackTableEntry(
			 	{9.0: 140, 10.0: 130, 19.0: 115, 12.0: 125, 18.0: 115}, nameIndex=276)
		}),
		'vertData': TrackData()
	}
```

Both `TrackData` and `TrackTableEntry` objects behave like dictionaries. They are nested inside each other, like a two-dimensional mapping: e.g., `table.horizData[-1.0][12.0] == -60`

Please let me know what you think,
Thanks.

/cc @jenskutilek @behdad @twardoch @moyogo @brawer 

Cf. https://github.com/behdad/fonttools/issues/375

### CODE REVIEW

**Comment by anthrotype** [comment]
this is the XML representation:

```xml
<trak>
    <version value="1.0"/>
    <format value="0"/>
    <horizData>
      <!-- nTracks=3, nSizes=5 -->
      <trackEntry value="-1.0" nameIndex="275">
        <!-- Tight -->
        <track size="9.0" value="-10"/>
        <track size="10.0" value="-30"/>
        <track size="12.0" value="-60"/>
        <track size="18.0" value="-63"/>
        <track size="19.0" value="-63"/>
      </trackEntry>
      <trackEntry value="0.0" nameIndex="303">
        <!-- Normal -->
        <track size="9.0" value="15"/>
        <track size="10.0" value="0"/>
        <track size="12.0" value="-5"/>
        <track size="18.0" value="-25"/>
        <track size="19.0" value="-25"/>
      </trackEntry>
      <trackEntry value="1.0" nameIndex="276">
        <!-- Loose -->
        <track size="9.0" value="140"/>
        <track size="10.0" value="130"/>
        <track size="12.0" value="125"/>
        <track size="18.0" value="115"/>
        <track size="19.0" value="115"/>
      </trackEntry>
    </horizData>
    <vertData>
      <!-- nTracks=0, nSizes=0 -->
    </vertData>
  </trak>
```

The respective name strings are printed as comments. 
When dumping to XML (or compiling), the track entries are sorted by incremental track value, and the per-size values also sorted by incremental size.

**Comment by brawer** [comment]
Oh, one last thing: Mind running MetaTools/buildTableList.py? That would re-generate the list of supported tables in the documentation.

**Comment by anthrotype** [comment]
I did that, right? https://github.com/anthrotype/fonttools/commit/4f5419fdec8dd1face4e3185d7146c1705b4de0f

**Comment by anthrotype** [comment]
oh, I see, the documentation.. well, that `MetaTools/buildTableList.py` needs to be updated since the "documentation.html" which it refers to has been removed..

**Comment by anthrotype** [comment]
@brawer ok, I've updated the `buildTableList.py` to write to README.md instead of the now deleted documentation.html. Let me know if it's ok, thanks.

**Comment by anthrotype** [comment]
:+1:

**Comment by behdad** [comment]
I had a vague memory that I had written code for this.  I found this in my git stashes...
```patch
commit c1393e7950db3c66d0c6ad7b133be8c14278af3d
Merge: ddb95b6 20e15c0
Author: Behdad Esfahbod <behdad@behdad.org>
Date:   Mon Nov 24 14:03:11 2014 -0800

    WIP on master: ddb95b6 Revert "Add back fontTools.xmlWriter"

diff --cc Lib/fontTools/ttLib/tables/otData.py
index 7c3f4bd,7c3f4bd..9097cd7
--- a/Lib/fontTools/ttLib/tables/otData.py
+++ b/Lib/fontTools/ttLib/tables/otData.py
@@@ -1013,4 -1013,4 +1013,38 @@@ otData = 
  		('uint16', 'SettingNameID', None, None, 'The name table index for the setting name.'),
  	]),
  
++	#
++	# trak
++	#
++
++	('trak', [
++		('Version', 'Version', None, None, 'Version of the trak table-initially set to 0x00010000.'),
++		('uint16', 'Format', None, None, 'Set to 0.'),
++		('Offset', 'HorizTrackData', None, None, 'Offset to TrackData for horizontal text (or 0 if none).'),
++		('Offset', 'VertTrackData', None, None, 'Offset to TrackData for horizontal text (or 0 if none).'),
++		('uint16', 'Reserved', None, None, 'Reserved (set to zero).'),
++	]),
++
++	('TrackData', [
++		('uint16', 'SettingValue', None, None, 'The setting.'),
++		('uint16', 'SettingNameID', None, None, 'The name table index for the setting name.'),
++	]),
++
++	('FeatureName', [
++		('uint16', 'FeatureType', None, None, 'Feature type.'),
++		('uint16', 'SettingsCount', None, None, 'The number of records in the setting name array.'),
++		('LOffset', 'Settings', None, None, 'Offset to setting table for this feature.'),
++		('uint16', 'FeatureFlags', None, None, 'Single-bit flags associated with the feature type.'),
++		('uint16', 'FeatureNameID', None, None, 'The name table index for the feature name.'),
++	]),
++
++	('Settings', [
++		('Setting', 'Setting', 'SettingsCount', 0, 'The setting array.'),
++	]),
++
++	('Setting', [
++		('uint16', 'SettingValue', None, None, 'The setting.'),
++		('uint16', 'SettingNameID', None, None, 'The name table index for the setting name.'),
++	]),
++
  ]
diff --cc Lib/fontTools/ttLib/tables/otTables.py
index 17cb80d,17cb80d..dae1fc3
--- a/Lib/fontTools/ttLib/tables/otTables.py
+++ b/Lib/fontTools/ttLib/tables/otTables.py
@@@ -504,6 -504,6 +504,7 @@@ _equivalents = 
  	'MathKern': ('TopRightMathKern', 'TopLeftMathKern', 'BottomRightMathKern',
  			'BottomLeftMathKern'),
  	'MathGlyphConstruction': ('VertGlyphConstruction', 'HorizGlyphConstruction'),
++	'TrackData': ('HorizTrackData', 'VertTrackData'),
  }
  
  #
```

but never finished it...

**Comment by anthrotype** [comment]
Interesting.. Does it work?

Who knows how many other treasures are hiding in your git stash ;)

**Comment by behdad** [comment]
Don't remember.  It might work.

On 15-10-07 04:05 PM, Cosimo Lupo wrote:
> Interesting.. Does it work?
> 
> Who knows how many other treasures are hiding in your git stash ;)
> 
> On Wed, Oct 7, 2015 at 8:57 PM, Behdad Esfahbod <notifications@github.com>
> wrote:
> 
>> I had a vague memory that I had written code for this. I found this in my
> git stashes...
>> ```patch
>> commit c1393e7950db3c66d0c6ad7b133be8c14278af3d
>> Merge: ddb95b6 20e15c0
>> Author: Behdad Esfahbod <behdad@behdad.org>
>> Date: Mon Nov 24 14:03:11 2014 -0800
>> WIP on master: ddb95b6 Revert "Add back fontTools.xmlWriter"
>> diff --cc Lib/fontTools/ttLib/tables/otData.py
>> index 7c3f4bd,7c3f4bd..9097cd7
>> --- a/Lib/fontTools/ttLib/tables/otData.py
>> +++ b/Lib/fontTools/ttLib/tables/otData.py
>> @@@ -1013,4 -1013,4 +1013,38 @@@ otData =
>> ('uint16', 'SettingNameID', None, None, 'The name table index for the
> setting name.'),
>> ]),
>>
>> ++ #
>> ++ # trak
>> ++ #
>> ++
>> ++ ('trak', [
>> ++ ('Version', 'Version', None, None, 'Version of the trak table-initially
> set to 0x00010000.'),
>> ++ ('uint16', 'Format', None, None, 'Set to 0.'),
>> ++ ('Offset', 'HorizTrackData', None, None, 'Offset to TrackData for
> horizontal text (or 0 if none).'),
>> ++ ('Offset', 'VertTrackData', None, None, 'Offset to TrackData for
> horizontal text (or 0 if none).'),
>> ++ ('uint16', 'Reserved', None, None, 'Reserved (set to zero).'),
>> ++ ]),
>> ++
>> ++ ('TrackData', [
>> ++ ('uint16', 'SettingValue', None, None, 'The setting.'),
>> ++ ('uint16', 'SettingNameID', None, None, 'The name table index for the
> setting name.'),
>> ++ ]),
>> ++
>> ++ ('FeatureName', [
>> ++ ('uint16', 'FeatureType', None, None, 'Feature type.'),
>> ++ ('uint16', 'SettingsCount', None, None, 'The number of records in the
> setting name array.'),
>> ++ ('LOffset', 'Settings', None, None, 'Offset to setting table for this
> feature.'),
>> ++ ('uint16', 'FeatureFlags', None, None, 'Single-bit flags associated with
> the feature type.'),
>> ++ ('uint16', 'FeatureNameID', None, None, 'The name table index for the
> feature name.'),
>> ++ ]),
>> ++
>> ++ ('Settings', [
>> ++ ('Setting', 'Setting', 'SettingsCount', 0, 'The setting array.'),
>> ++ ]),
>> ++
>> ++ ('Setting', [
>> ++ ('uint16', 'SettingValue', None, None, 'The setting.'),
>> ++ ('uint16', 'SettingNameID', None, None, 'The name table index for the
> setting name.'),
>> ++ ]),
>> ++
>> ]
>> diff --cc Lib/fontTools/ttLib/tables/otTables.py
>> index 17cb80d,17cb80d..dae1fc3
>> --- a/Lib/fontTools/ttLib/tables/otTables.py
>> +++ b/Lib/fontTools/ttLib/tables/otTables.py
>> @@@ -504,6 -504,6 +504,7 @@@ _equivalents =
>> 'MathKern': ('TopRightMathKern', 'TopLeftMathKern', 'BottomRightMathKern',
>> 'BottomLeftMathKern'),
>> 'MathGlyphConstruction': ('VertGlyphConstruction', 'HorizGlyphConstruction'),
>> ++ 'TrackData': ('HorizTrackData', 'VertTrackData'),
>> }
>>
>> #
>> ```
>> but never finished it...
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/behdad/fonttools/pull/381#issuecomment-146310662
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/behdad/fonttools/pull/381#issuecomment-146313081>.
> 

-- 
behdad
http://behdad.org/

**Comment by anthrotype** [comment]
i’ll try.

but is the advantage of having it done through otData.py, etc. instead of the traditional ttLib way?





--
Cosimo

**Comment by behdad** [comment]
> but is the advantage of having it done through otData.py, etc. instead of the traditional ttLib way?

Less code to maintain!

**Comment by behdad** [comment]
In some distant future we might switch everything to a revised data-driven model.  Whenever that happens, the otData stuff will be converted automatically.  Whereas open-coded tables need to be, well, converted or stay as is...  It's just easier to make changes across the whole library with the data-driven model.

Not really important for this table per se, but, eg, for something like morx table, I definitely don't want to see handcoding...

**Pull request merged**
