### PR TITLE
[macCreatorType] disable workaround in py27 for setting as well getting

### PR DESCRIPTION
**Pull request by anthrotype**
I know nowadays one no longer needs to set the creator and type on a mac, but because we already fixed the "getting" part, we may as well fix the "setting" one...

### CODE REVIEW

**Comment by behdad** [comment]
The Python bug you referred to before, suggested that only one of set and get was affected.  Can you check again?

**Comment by anthrotype** [comment]
Yes, I did check. The setter is indeed currently broken on 2.7, unless we disable that workaround.

**Comment by behdad** [comment]
No no.  What I'm saying is this paragraph [0]:

"""
Annoyingly enough only 
GetCreatorAndType needed fixing, SetCreatorAndType already did the right 
thing (makeing the two functions inconsistent with each other).
""""

So I think we should remove the hack for Set, not contain it to < 2.7.

[0] http://bugs.python.org/issue1594

**Comment by anthrotype** [comment]
I see what you mean now. I'll check with pyhton 2.6 as well and let you know

**Comment by anthrotype** [comment]
Indeed, you're right. With Python 2.6.9, the current setting function (the one with the workaround) writes the creator and type with reversed strings. So we should disable the workaround for all python versions, not just 2.7.

**Pull request merged**
