### PR TITLE
run coverage.py on Travis and upload report to coveralls

### PR DESCRIPTION
**Pull request by anthrotype**
I really recommend that we use [coverage.py](http://coverage.readthedocs.org/en/coverage-4.0.3) to measure our test suite coverage. It's really cool.
We even have a badge on the homepage, so we'd better use it! :)
However that link leads nowhere... https://coveralls.io/r/behdad/fonttools
Perhaps @behdad created it in the past but then decided to close it?

### CODE REVIEW

**Comment by behdad** [comment]
That was my goal.  Not sure where I dropped the ball.  Anyway, enabling now.

**Comment by anthrotype** [comment]
Thank you! 🎉

**Comment by behdad** [comment]
First numbers in: 71%.  Not bad at all!

I promise to add tests to mtiLib soon!

**Comment by anthrotype** [comment]
@behdad perhaps it would be better to disable the email notification from coveralls.io on every single push? It's kind of noisy...

**Comment by behdad** [comment]
It's set to only email if coverage changed by +/- 3% only.

On Mon, Apr 11, 2016 at 2:08 AM, Cosimo Lupo <notifications@github.com>
wrote:

> @behdad <https://github.com/behdad> perhaps it would be better to disable
> the email notification from coveralls.io on every single push? It's kind
> of noisy...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/behdad/fonttools/pull/571#issuecomment-208242582>
>



-- 
behdad
http://behdad.org/

**Pull request merged**
