### PR TITLE
[snippets] add gbk codepoint conversion in convert cmap format process

### PR DESCRIPTION
**Pull request by bihicheng**
add gbk codepoint conversion in convert cmap format process

### CODE REVIEW

**Comment by behdad** [comment]
Humm.  Where does the module gbk come from?

**Comment by bihicheng** [comment]
from me. :)

**Comment by bihicheng** [comment]
come from a lua script.

**Comment by behdad** [comment]
So, Python codecs didn't have that?

**Comment by bihicheng** [comment]
I tried the python codecs first, but it have not method to do that,  then I use this way now.

**Comment by davelab6** [comment]
@behdad what additional steps are needed to merge this, or should it be closed?

**Comment by behdad** [comment]
I'm not sure if this is suitable and don't have to check it more.

**Pull request closed without merging**
