### PR TITLE
add "ignoreSinglePoints" argument to bounds pen

### PR DESCRIPTION
**Pull request by anthrotype**
see discussion:
https://github.com/behdad/fonttools/pull/450
https://github.com/typemytype/booleanOperations/pull/20

cc @adrientetar @behdad

### CODE REVIEW

**Comment by adrientetar** [comment]
See #450, the ufo3 tools (amongst which ufoLib) don't draw anchors in the pen anymore, so we're good when using ufoLib.

**Comment by anthrotype** [comment]
I'm not sure I understand, Adrien. What do you mean "we are good"? Don't we want to make the fonttools bounds pens behave like the robofab ones in certain circumstances (e.g. in booleanOperations' BooleanContour)?

**Comment by adrientetar** [comment]
Right, defcon doesn't draw anchors like this anymore in the ufo3 branch but booleanOperations still does. Hmm... I'm not sure we should alter fontTools to cater for what's essentially a hack in ufo2 tools.

**Comment by adrientetar** [comment]
I'll ask Tal about this.

**Pull request merged**
