### PR TITLE
add Appveyor support

### PR DESCRIPTION
**Pull request by anthrotype**
Currently we only run tests on Ubuntu Linux via Travis.
I'd like to also run the tests on Windows Python, since there are sometimes differences in the implementations (e.g. newlines, binary vs text, etc.).
This adds a `.appveyor.yml` to set up the Appveyor CI.
I'm not sure if I can enable the project myself or @behdad needs to do it on his side.

Anyway, here's the link to the current build running from my fork:
https://ci.appveyor.com/project/anthrotype/fonttools/build/1.0.29

(fingers crossed)

### CODE REVIEW

**Comment by anthrotype** [comment]
build passed, merging!
https://ci.appveyor.com/project/anthrotype/fonttools

@behdad it looks like I can enable it myself from my Appveyor projects panel. Let's see...

**Comment by anthrotype** [comment]
hmm, the URL looks like this:
https://ci.appveyor.com/project/anthrotype/fonttools-qis1l
Is that a problem?

**Comment by behdad** [comment]
Thanks!  Is it configured to notify IRC and Google Group in case of failures?

**Comment by anthrotype** [comment]
Yes, email only though, as Appveyor does not support IRC notifications like
Travis.

Thanks! Is it configured to notify IRC and Google Group in case of failures?

—
Reply to this email directly or view it on GitHub
<https://github.com/behdad/fonttools/pull/433#issuecomment-164160134>.

**Comment by anthrotype** [comment]
hey @behdad, I noticed the Appveyor builds are not being triggered automatically on pushes or pull requests to behdad/fonttools.. I think you need to enable it yourself from your Appveyor account.

just go to your appveyor, click new project and enable the fonttools repo. Also, you need to add this in the project's settings, since I renamed the default `appveyor.yml` to `.appveyor.yml` to make it invisible:

screenshot

once you've done that, we can update the README.md badge URL to point to the official Appveyor project page.

Thanks

**Comment by behdad** [comment]
Done.

**Comment by anthrotype** [comment]
cool, thanks!

https://ci.appveyor.com/project/behdad/fonttools

**Comment by anthrotype** [comment]
hmm... the [first build](https://ci.appveyor.com/project/behdad/fonttools/build/1.0.1) returned this error:

```
Specify a project or solution file. The directory does not contain a project or solution file.
```

Did you set `.appveyor.yml` (with the starting dot) as custom configuration `.yml` file name as in the above screenshot?

**Comment by behdad** [comment]
I had .appveyor.xml instead of .appveyor.yml.  Fixed.

**Comment by anthrotype** [comment]
thank you!

**Comment by anthrotype** [comment]
last thing: could you retrieve the correct url for the build status badge from your settings page? I tried modifying it but it's still pointing to the old one.

**Comment by anthrotype** [comment]
I mean, the link now points to the new Appveyor project page, but the SVG is still referencing the old one (sorry for the little mess)

**Comment by behdad** [comment]
done

**Comment by anthrotype** [comment]
:+1:

**Pull request merged**
