### PR TITLE
Change whitespace in subset.py to conform with Python style guide

### PR DESCRIPTION
**Pull request by brawer**
The Python style (outside of Google) is four spaces for indentation.
After this change, pylint still has complaints about this file,
but these formatting changes will probably improve the health
metrics of landscape.io. Personally, I couldn't care less about
whitespace, but it is hard to spot actual problems in a sea
of lint warnings.

### CODE REVIEW

**Comment by behdad** [comment]
I remember I had all tabs; for the Open Source release, Roozbeh convinced me that it's Google recommendation to use two spaces, so I did that.  When I merged the subsetter back into fonttools, I wish I had kept the tabs, which is what the rest of the codebase uses.

I'll merge this now, but we should change our landscape.io setting to ignore whitespace issues.  There are a couple of outstanding Pull Requests against the subsetter that I would need to rebase.

**Comment by behdad** [comment]
Should we just change to 8, and use tabs now that we touched it?

**Comment by brawer** [comment]
Or, perhaps, we should try to comply with PEP8?
https://www.python.org/dev/peps/pep-0008/

I wouldn't want to spend too much time on style things (the discussions can
be such a time sink), but there's certainly some advantage to being in line
with other Python code out there. We could try to run this on the codebase:
https://pypi.python.org/pypi/autopep8/1.1.1

Shall I give it a try?

-- Sascha

2015-05-07 11:16 GMT+02:00 Behdad Esfahbod <notifications@github.com>:

**Comment by mvasilkov** [comment]
I second PEP8 so very much.

**Comment by brawer** [comment]
Here's a sample change generated by autopep8:
https://github.com/behdad/fonttools/pull/261

-- Sascha

2015-05-07 14:15 GMT+02:00 я котик пур-пур <notifications@github.com>:

**Comment by brawer** [comment]
And here's the same PEP8 reformatting for an entire directory:
https://github.com/behdad/fonttools/pull/263

2015-05-07 14:25 GMT+02:00 Sascha Brawer <sascha@brawer.ch>:

**Pull request merged**
