### PR TITLE
[feaLib] ignore stray semicolons

### PR DESCRIPTION
**Pull request by anthrotype**
This addresses issue #641.

in https://github.com/behdad/fonttools/commit/7eed24725f33c76d033e40888d865e13d47622c2, Sascha allowed the `include` statement to not be followed by a semicolon.
However, the symbol is not eaten up by the Lexer, but is passed on to the Parser, which barks at it because it does not expect a stray SYMBOL ";" at the top level of a feature file.

I tested with makeotf, and confirmed that it ignores any extra semicolons which appear in a feature file. I guess we can do the same.

### CODE REVIEW

**Comment by anthrotype** [comment]
kind of, yeah.

Inside blocks, the semicolon is already ignored in a similar way:
https://github.com/behdad/fonttools/blob/master/Lib/fontTools/feaLib/parser.py#L1114-L1115

only in top-level main parser loop it isn't, hence the error in #641

**Comment by justvanrossum** [comment]
I'm sure I'm notpicking (and I do care most about the bug being fixed, so thank you!) but your wording sounds backwards to me: the ; is (as far as I can tell) part of the statement, and the special case is to allow it to be skipped, not to allow it to be present :) (Regardless of how it's implemented.)

**Comment by anthrotype** [comment]
I see what you mean. That was in fact the original implementation (semicolon as part of the the `include` statement), which was more in line with how the spec defines it:
http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#3

Also see the discussion here:

https://github.com/behdad/fonttools/issues/552

https://github.com/adobe-type-tools/afdko/issues/114

**Comment by brawer** [comment]
Thank you! makeotf also accepts a feature file with the content `;;;`, so we should too.

**Pull request merged**
