### PR TITLE
[OS/2] update fsFirstCharIndex and fsLastCharIndex upon compile

### PR DESCRIPTION
**Pull request by anthrotype**
this addresses a [request](https://github.com/behdad/fonttools/issues/255) by @lemzwerg to recalculate the `fsFirstCharIndex` and `fsLastCharIndex` of OS/2 table while reassembling a font.

I added a method to the OS/2 table class, which is called upon compiling that table. It simply gathers all codes specified in cmap subtables (3, 0) or (3, 1) and takes the min/max among these.

Should this be the default behaviour when compiling the OS/2 table (like in the current patch), or it should be controlled through some sort of option?

### CODE REVIEW

**Comment by lemzwerg** [comment]
Very nice!  Thanks for the quick patch.  My opinion is that a font shouldn't lie.  Consequently, automatically computed values should be used as much as possible to avoid human failure.  I plead for your code to be integrated unconditionally.

**Comment by behdad** [comment]
Can you add a comment to the XML output, ala the maxp table, to say that these are autocomputed?

**Comment by anthrotype** [comment]
do you mean a general comment at the top of the table, like in maxp or loca:

    writer.comment("Most of this table will be recalculated by the compiler")

or a specific one which only refers to `fsFirstCharIndex` and `fsLastCharIndex`?

**Comment by behdad** [comment]
Maybe be more specific, instead of "Most of this table", say which fields are recalculated.

**Comment by anthrotype** [comment]
OK, I have added a comment at the top OS/2 table XML output , which now reads like that:

```xml
 <OS_2>
    <!-- The fields 'fsFirstCharIndex' and 'fsLastCharIndex'
         will be recalculated by the compiler -->
 <version value="4"/>
```

**Comment by anthrotype** [comment]
OK, now using isUnicode() and with the commits squashed into one

**Comment by lemzwerg** [comment]
Thanks!

**Pull request merged**
