### PR TITLE
boundsPen: ignore single points aka. anchors

### PR DESCRIPTION
**Pull request by adrientetar**
This brings the BoundsPen inline with that of robofab and uses only outlines for the calculation of bounds.

See typemytype/booleanOperations#20.

### CODE REVIEW

**Comment by behdad** [comment]
Another, simpler, approach is to modify updateBounds instead using an optional argument, to ignore rectangles with zero height and width.

**Comment by anthrotype** [comment]
hmm.. shouldn't it be optional to ignore single-point contours?

**Comment by anthrotype** [comment]
Adrien's patch makes ignoring anchors the default behaviour and there's no optional argument, like robofab's boundsPen.

In my patch, I kept the current behavior and added an optional "ignoreSinglePoints":
https://github.com/anthrotype/fonttools/commit/dc2ef2e341e4ab868801b4b3ff5a867114f182e4

**Comment by anthrotype** [comment]
I haven't pulled a request yet because I wasn't sure whether fontTools.pens is the right place for this...

**Comment by anthrotype** [comment]
> modify updateBounds... to ignore rectangles with zero height and width

sorry, I don't understand..
`updateBounds` takes a rectangle and a point and must returns a new, possibly modified, rectangle. What do you mean by "ignore rectangles with zero height and width"?

**Comment by adrientetar** [comment]
My question so far has been "Why would you not ignore anchors when calculating the bounds of a glyph?". 
The robofab pen says it's "temporarily(?)" making a pen that does ignore anchors. Is there anyone out there who needs the pen to factor in anchors? If not, we should fix it now.

> Another, simpler, approach is to modify updateBounds instead using an optional argument, to ignore rectangles with zero height and width.

Rectangles always start by being zero height and width since it's built incrementally from each point in the contour. I think the right elision approach is indeed the robofab one: store the startPoint instead of processing it and do factor it when an actual line/curve segment follows.

**Comment by behdad** [comment]
> modify updateBounds... to ignore rectangles with zero height and width
> 
> sorry, I don't understand..
> updateBounds takes a rectangle and a point and must returns a new, possibly modified, rectangle. What do you mean by "ignore rectangles with zero height and width"?

Oops.  My bad.  I thought it merges two rectangles.

**Comment by anthrotype** [comment]
> "Why would you not ignore anchors when calculating the bounds of a glyph?"

I don't know.. I guess a single-point contour in a TrueType glyf might be interpreted as an open (invisible) contour, rather than an "anchor".

**Comment by moyogo** [comment]
> My question so far has been "Why would you not ignore anchors when calculating the bounds of a
> glyph?". 

In the glyf table or in UFO3, single points are not anchors.
In UFO2, single points are either anchors or single points, depending on the interpretation whether they are named or not.

**Comment by moyogo** [comment]
BTW, these single points could be useful in TTF. A GPOS anchor can be attached to a single point that can be hinted with TT instructions.

**Comment by adrientetar** [comment]
> In the glyf table or in UFO3, single points are not anchors.

Afaict in the pen protocol, we have no way to tell anchors and single-points apart. It's what we're working with here and I don't think that it changed with ufo3.

> I don't know.. I guess a single-point contour in a TrueType glyf might be interpreted as an open (invisible) contour, rather than an "anchor".

Yes. Probably. But even if we have that, is it worth including it in the bounds? 
Between including anchors which aren't outlines and excluding points which won't even display, I think the choice is straight-forward. 
Ultimately if there's a problem of expressivity it should be adressed independently of what's being done in this PR. I wouldn't argue that current behavior is less wrong than the one proposed in this PR.

> BTW, these single points could be useful in TTF. A GPOS anchor can be attached to a single point that can be hinted with TT instructions.

Right, I know anything's possible with the power of TT instructions. Is such a technique actually used in some fonts? I'd be surprised that people go ahead using single points like this in production, given that some rasterizers may behave strangely when it comes to rendering of bounds calculation as we see here.

**Comment by behdad** [comment]
> Right, I know anything's possible with the power of TT instructions. Is such a technique actually used in some fonts? I'd be surprised that people go ahead using single points like this in production, given that some rasterizers may behave strangely when it comes to rendering or bounds calculation as we see here.

We've definitely seen this in fonts in the wild.  Some Noto fonts probably include it as well.

**Comment by anthrotype** [comment]
so, what's the consensus then? Should we keep the current default behavior and allow to optionally "ignoreSinglePoints", or change the behavior to always ignore them, or simply do nothing (and let clients subclass BoundsPen if they like)?
I personally don't have a strong opinion, and I'm more confused than before.

**Comment by behdad** [comment]
I'm fine if we change this in a backwards-compatible way (ie, default to previous behavior).

**Comment by adrientetar** [comment]
Alright, I just looked at defcon's source again and it seems that in the ufo3 branch glyph.draw(pen) doesn't "draw" anchors while it did in ufo2. 
This behavior seems to bring the (UFO-owned) pointPen inline with segmentPen in terms of what it's expressing, though the issue remains for ufo2.

This was done in commit https://github.com/typesupply/defcon/commit/73a677b3d3a5f228f0e056a7182989a93454fad5#diff-0d4ef48dc0f6e887190b3bc5a98187b4.

**Comment by adrientetar** [comment]
ufoLib doesn't use the anchors hack anymore so as far as I'm concerned, we're good here.

**Pull request closed without merging**
