### PR TITLE
TTGlyphPen tests

### PR DESCRIPTION
**Pull request by jamesgk**
This adds tests with the existing TTX test data, and some simple unit tests. It also fixes issues with the pen itself! Tests are nice.

### CODE REVIEW

**Comment by anthrotype** [comment]
Excellent!! :+1: 

just one thing:
https://github.com/jamesgk/fonttools/blob/pen-tests/Lib/fontTools/pens/ttGlyphPen.py#L114

```diff
-glyph.program.fromBytecode("")
+glyph.program.fromBytecode(b"")
```

**Comment by anthrotype** [comment]
All looks good to me, except for that `TypeError` spotted by Travis when initialising `array.array` with an empty `str` -- it should be `bytes` for Python3.

Thanks!

**Comment by anthrotype** [comment]
Can I merge now or do you have other commits to push?

**Comment by jamesgk** [comment]
Yea, this is done.

**Pull request merged**
