### PR TITLE
[setup.py] monkeypatch py_compile to halt compilation on syntax errors

### PR DESCRIPTION
**Pull request by anthrotype**
This is an attempt to fix issue https://github.com/behdad/fonttools/issues/290.
It uses a trick found [here](http://stackoverflow.com/a/2240549) which monkeypatches the py_compile.compile function used by distutils, so that it will raise an exception instead of a warning on any errors found while bytecompiling the modules.
With this the `make all` command will properly fail.

### CODE REVIEW

**Comment by anthrotype** [comment]
the Python 3 builds on Travis were failing because of mixed tabs and spaces (in Python 3 this raises a TabError). I fixed it a subsequent commit.
Shall I open a separate PR for that, is it ok like this?

**Comment by anthrotype** [comment]
btw, it was actually thanks to the patch that the TabError in merge.py could be found.. I guess one more reason to have `make` return failure on compilation errors.

**Comment by behdad** [comment]
Thanks Cosimo.

I also added you as a collaborator on the repo so you can push trivial patches directly.

**Comment by anthrotype** [comment]
Thank you!

**Pull request merged**
