### PR TITLE
Add unload method to area pen

### PR DESCRIPTION
**Pull request by jamesgk**
I think this is a worthwhile convenience function for the common case
of calculating the area of many glyphs in succession.

### CODE REVIEW

**Comment by behdad** [comment]
I'm not a huge fan.  I'd be more interested in adding a reset() if anything.  I personally think having users set value to zero manually is simpler and better, at least until we figure out a more uniform way.  The reason I called the value 'value' and not 'area' is because I have this vague idea about having a class of pens that calculate a value, and all put it in pen.value.  That might not be super useful, but for now let's not add new API.

**Comment by anthrotype** [comment]
What if we make 'value' a property getter which returns the value and also resets it? Just sayin'

**Comment by anthrotype** [comment]
Actually that would be confusing, nevermind.

**Comment by behdad** [comment]
> What if we make 'value' a property getter which returns the value and also resets it? Just sayin'

The "also resets it" is a big NO based on the "minimize surprise" principle.

**Comment by adrientetar** [comment]
> What if we make 'value' a property getter which returns the value and also resets it? Just sayin'

A pop() function would make more sense, FWIW. Anyway this is bikeshed.

**Pull request closed without merging**
