### PR TITLE
Add pen which draws to TrueType glyphs

### PR DESCRIPTION
**Pull request by jamesgk**

### CODE REVIEW

**Comment by behdad** [comment]
lgtm other than the comment above.  Can you also add the cffGlyphPen?

**Comment by anthrotype** [comment]
It looks good to me. Maybe later we can also add some tests.
Thank you James! :+1:

**Comment by anthrotype** [comment]
@jamesgk Can we merge this now or you need to add more changes?
It looks fine to me.

**Comment by jamesgk** [comment]
Yea, I think this is fine. We'll do the cffGlyphPen in another PR.

**Comment by anthrotype** [comment]
Thanks a lot for your work!

**Comment by behdad** [comment]
> Handle None here? See docstring comments for qCurveTo in basePen. In particular this part:
> 
> ↦       ↦       The last argument (normally the on-curve point) may be None. 
> ↦       ↦       This is to support contours that have NO on-curve points (a rarely 
> ↦       ↦       seen feature of TrueType outlines).

Please address this and add tests.

**Comment by anthrotype** [comment]
@behdad isn't this OK? 
https://github.com/jamesgk/fonttools/commit/b916c5bb935da2d1a55fa0706cb372ec3e54436e

**Comment by behdad** [comment]
> @behdad isn't this OK?
> jamesgk@b916c5b

Oh sorry I didn't see that.  Thanks!

We should add tests for this pen.

**Comment by anthrotype** [comment]
yes, we should.

**Pull request merged**
