### PR TITLE
Use PEP-8 whitespace conventions for fontTools/ttLib/tables

### PR DESCRIPTION
**Pull request by brawer**
Changes were automatically generated with autopep8.

### CODE REVIEW

**Comment by behdad** [comment]
I'm rather hesitant to make such huge cosmetic changes, specially given that there are still people transitioning from the old fonttools, so I don't want to disrupt the code base drastically.

Should we just tune landscape.io re whitespace instead?

**Comment by brawer** [comment]
Sure. Personally, I'd rather spend energy on actual changes than on style
issues anyway.

-- Sascha

**Comment by behdad** [comment]
Agreed.  Lets let this go for now and I'll try to adjust landscape.io settings a bit.

**Comment by behdad** [comment]
I'm watching this now:
https://www.youtube.com/watch?v=wf-BqAjZb8M

**Pull request closed without merging**
