### PR TITLE
fix "indentation contains mixed spaces and tabs" errors reported by Landscape

### PR DESCRIPTION
**Pull request by miguelsousa**

### CODE REVIEW

**Comment by anthrotype** [comment]
I'm not 100% sure it's a good idea to "pep8ify" everything just to make Landscape.io happy..
Have you watched Raymond Hettinger's talk "Beyond PEP8"?
http://youtu.be/wf-BqAjZb8M

**Comment by miguelsousa** [comment]
@anthrotype I did watched that, and I'm not trying to pep8ify or make Landscape happy. The goal was to help surface the real errors.

**Comment by anthrotype** [comment]
Thank Miguel, I'll have a closer look then.
I was mainly concerned about possible merge conflicts in other open pull requests.

**Comment by behdad** [comment]
pep8 thread is https://github.com/behdad/fonttools/pull/263.

I like this though.  Should be safe to merge even.

**Pull request merged**
