### PR TITLE
Fix xml-roundtripping of CFF fonts (name-keyed & cid-keyed)

### PR DESCRIPTION
**Pull request by miguelsousa**
Something like this was failing,
```python
from fontTools.ttLib import TTFont

font = TTFont()
font.importXML('myFont.ttx')
font.saveXML('myNewFont.ttx')
```

### CODE REVIEW

**Comment by anthrotype** [comment]
Thanks Miguel. I wonder, does the inline comment have anything to do with the proposed patch?
> `# index is not defined at this point. Read R. ?`

**Comment by miguelsousa** [comment]
@anthrotype no, but the second commit addresses it. Now a CID font xml-roundtrips, whereas it didn't before. I've updated the title of the PR accordingly.

**Comment by anthrotype** [comment]
Thank you. I don't know enough about CFF to assess this, so I'll cc @behdad or @readroberts

**Comment by readroberts** [comment]
This patch is correct and safe. The FDSelect index table is present in a CFF  if and only if the FDArray index table is present.

**Comment by anthrotype** [comment]
Thank you Read!

**Pull request merged**
